name: CI

on: [push]

jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Static Testing
        uses: cypress-io/github-action@v2
        with:
          command: yarn validate

      - name: E2E Testing
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: yarn test:e2e
